const iconfont: string[] = [
  "icon-kankanshuxiexiezi",
  "icon-jianshenlejieyixia",
  "icon-heshoujiguo",
  "icon-lianshufa",
  "icon-shafatang",
  "icon-shuijue",
  "icon-maidongxi",
  "icon-hediannaoguo",
  "icon-shangtian",
  "icon-arthur",
  "icon-alexa",
  "icon-anna",
  "icon-edward",
  "icon-claire",
  "icon-chloe",
  "icon-emily",
  "icon-harold",
  "icon-clara",
  "icon-hanna",
  "icon-george",
  "icon-finn",
  "icon-frank",
  "icon-henry",
  "icon-freddy",
];

export default iconfont;
